[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"


[project]
name = "robotframework-ibmmq"
version = "0.1.3"
authors = [
  { name="Niels Janssen"},
]
maintainers = [
  { name="Niels Janssen"},
]
description = "A Robotframework library for IBM MQ"
keywords = ["robotframework", "ibm", "mqlibrary"]
readme = "README.md"
license = "EUPL-1.2"
requires-python = ">=3.9.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Testing",
    "Framework :: Robot Framework",
    "Framework :: Robot Framework :: Library",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "ibmmq (>=2.0.0,<3.0.0)"
]

[dependency-groups]
dev = [
    "pyyaml>=6.0.3",
]
build = ["python-semantic-release>=10.5.3"]

deploy = ["twine", "build", "wheel"]


[project.optional-dependencies]
rf70 = ["robotframework>=7.0.0,<7.1.0"]
rf71 = ["robotframework>=7.1.0,<7.2.0"]
rf72 = ["robotframework>=7.2.0,<7.3.0"]
rf73 = ["robotframework>=7.3.0,<7.4.0"]
rf74 = ["robotframework>=7.4.0,<7.5.0"]

[tool.uv]
conflicts = [
    [
        {extra = "rf70"},
        {extra = "rf71"},
        {extra = "rf72"},
        {extra = "rf73"},
        {extra = "rf74"},
    ]
]

[tool.semantic_release]
commit_parser = "conventional"
version_toml = ["pyproject.toml:project.version"]
allow_zero_version = true
build_command = "uv build"

[project.urls]
Homepage = "https://github.com/nluwv/robotframework-ibmmq"
Documentation = "https://robotframework-ibmmq.netlify.app/IBMMQLibrary.html"
Repository = "https://github.com/nluwv/robotframework-ibmmq.git"
Issues = "https://github.com/nluwv/robotframework-ibmmq/issues"

[tool.uv.build-backend]
module-name = "IBMMQLibrary"
